version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"              # Root directory (where your build.gradle is)
    schedule:
      interval: "monthly"       # Options: "daily", "weekly", "monthly"
      time: "04:00"             # Optional: UTC time
    open-pull-requests-limit: 2
    commit-message:
      prefix: "deps"
