[versions]
java = "25"
minecraft = "26.1"
loom = "1.15.5"
fabric = "0.144.3+26.1"
fabricLoader = "0.18.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

[plugins]
loomID = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
